apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: my-app-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
