apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
  namespace: my-app-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: snaveenkpn/my-node-app:3
          ports:
            - containerPort: 7500
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: my-node-app-config
