apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: my-app-namespace
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 7500
  type: NodePort
